
# Generated by Django 4.2.7 on 2023-11-29 19:15
# Generated by Django 4.2.7 on 2023-11-30 11:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_guide_user'),
        ('main_app', '0002_order_guide_orders'),
    ]

    operations = [
    ]
