# Generated by Django 4.2.7 on 2023-11-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_comment_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.guide'),
        ),
    ]
